---

- name: Copying keys
  copy:
    content: "{{ item.key }}"
    dest: "{{ openssl_keys_path }}/{{ item.name }}"
    owner: "{{ item.owner | default(openssl_default_key_owner) }}"
    group: "{{ item.group | default(openssl_default_key_group) }}"
    mode: "{{ item.mode | default('0640') }}"
  with_items: "{{ openssl_keys }}"

- name: Copying certs
  copy:
    content: "{{ item.cert }}"
    dest: "{{ openssl_certs_path }}/{{ item.name }}"
    owner: "{{ item.owner | default(openssl_default_cert_owner) }}"
    group: "{{ item.group | default(openssl_default_cert_group) }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items: "{{ openssl_certs }}"

- name: Creating self-signed server SSL cert
  command: >
    openssl req -new
      -x509
      -nodes
      -extensions v3_ca
      -days {{ item.days | default(3650) }}
      -subj "/C={{ item.country | default('') }}/ST={{ item.state | default('') }}/L={{ item.city | default('') }}/O={{ item.organization | default('') }}/OU={{ item.unit | default('') }}{% if item.domains is defined %}{% for domain in item.domains %}/CN={{ domain }}{% endfor %}{% else %}/CN={{ item.name }}{% endif %}/emailAddress={{ item.email | default('') }}"
      -keyout {{ openssl_keys_path }}/{{ item.name }}.key
      -out {{ openssl_certs_path }}/{{ item.name }}.crt
  args:
    creates: "{{ openssl_certs_path }}/{{ item.name }}.crt"
  with_items: "{{ openssl_self_signed }}"

- name: Generating CSR from Certificate
  when: openssl_generate_csr
  command: >
    openssl req -new
      -subj "/C={{ item.country | default('') }}/ST={{ item.state | default('') }}/L={{ item.city | default('') }}/O={{ item.organization | default('') }}/OU={{ item.unit | default('') }}{% if item.domains is defined %}{% for domain in item.domains %}/CN={{ domain }}{% endfor %}{% else %}/CN={{ item.name }}{% endif %}/emailAddress={{ item.email | default('') }}"
      -key {{ openssl_keys_path }}/{{ item.name }}.key
      -out {{ openssl_csrs_path }}/{{ item.name }}.csr
  args:
    creates: "{{ openssl_csrs_path }}/{{ item.name }}.csr"
  with_items: "{{ openssl_self_signed }}"

